spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate


